# Generated by Django 5.1 on 2024-08-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
