# Generated by Django 4.2.15 on 2024-08-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_object_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default=(('photo', 'Photo'),), max_length=50),
            preserve_default=False,
        ),
    ]
